In [6]:
import numpy as np
import pandas as pd

data_path = 'C:\Users\evgeny demekhin\Desktop\kaggle/'

test_df = pd.read_csv(data_path + 'test.csv')
# train_df = pd.read_csv(data_path + 'train.csv')
client_df = pd.read_csv(data_path + 'cliente_tabla.csv')
product_df = pd.read_csv(data_path + 'producto_tabla.csv')
townstate_df = pd.read_csv(data_path + 'town_state.csv')
# assert isinstance(train_df, pd.DataFrame)
# print test_df
print 42

42

In [5]:
print test_df

              id  Semana  Agencia_ID  Canal_ID  Ruta_SAK  Cliente_ID  \
0              0      11        4037         1      2209     4639078
1              1      11        2237         1      1226     4705135
2              2      10        2045         1      2831     4549769
3              3      11        1227         1      4448     4717855
4              4      11        1219         1      1130      966351
5              5      11        1146         4      6601     1741414
6              6      11        2057         1      4507     4659766
7              7      10        1612         1      2837     4414012
8              8      10        1349         1      1223      397854
9              9      11        1461         1      1203     1646915
10            10      11        1124         1      1118     4555688
11            11      10        1336         1      1069     4387996
12            12      11        1239         1      1125      290608
13            13      10        1217         1      1143     4446449
14            14      10        1312         1      2056       69110
15            15      11        1227         1      2115     1034925
16            16      11        2071         1      1203       91580
17            17      11        3211         1      1016      325074
18            18      10        1629         1      1612     2325923
19            19      11       23719         1      2813     4752270
20            20      11        1347         1      2153     2257091
21            21      11        2653         1      1048     5885765
22            22      10        1477         4      4714     4670562
23            23      11        1232         1      1211      245366
24            24      11        2216         1      1151     2197573
25            25      11        1227         1      2822     3342223
26            26      10        3214         1      1627     4721398
27            27      11        1420         1      2134     1500391
28            28      11        1137         1      1064     4461695
29            29      11        2012         1      1158     1485041
...          ...     ...         ...       ...       ...         ...
6999221  6999221      11        1613         1      1024     2392365
6999222  6999222      10        1552         1      2003       31357
6999223  6999223      10        1557         1      1026     1951715
6999224  6999224      11        2032         1      2056      241145
6999225  6999225      10        1137         1      1470      260348
6999226  6999226      11        1245         1      2804     1419434
6999227  6999227      11        3215         1      4459       58834
6999228  6999228      10        1215         1      1605     2379288
6999229  6999229      10        4051         1      1106      122768
6999230  6999230      11        2031         1      1051     4477847
6999231  6999231      11        1636         1      1101     1740273
6999232  6999232      10        1223         1      1257      939061
6999233  6999233      10        2016         1      1316     1345165
6999234  6999234      11        4049         1      1141     1067683
6999235  6999235      11        2032         1      1155      241197
6999236  6999236      11       24049         1      4502     4416986
6999237  6999237      10        1618         1      4416     2447781
6999238  6999238      10        1336         1      2106     1203863
6999239  6999239      11        1427         1      2801     1373090
6999240  6999240      11        1620         1      1242     1611046
6999241  6999241      10        1378         1      1265     2021090
6999242  6999242      10        1338         1      1201      789056
6999243  6999243      11        1631         1      2806     1526987
6999244  6999244      11        1420         1      1119     1621931
6999245  6999245      10        1333        11      3905     1905253
6999246  6999246      11        2057         1      1153     4379638
6999247  6999247      10        1334         1      2008      970421
6999248  6999248      11        1622         1      2869      192749
6999249  6999249      11        1636         1      4401      286071
6999250  6999250      11        1625         1      1259      978760

         Producto_ID
0              35305
1               1238
2              32940
3              43066
4               1277
5                972
6               1232
7              35305
8               1240
9              43203
10              1278
11              2233
12              4270
13              1240
14             43274
15             37361
16             43200
17              1150
18              4270
19             35456
20             30552
21              1125
22             35525
23              1150
24              1232
25             43285
26             36920
27             37361
28              2233
29             41938
...              ...
6999221         1109
6999222        43084
6999223        31393
6999224        43316
6999225        35651
6999226        35305
6999227        43069
6999228        31719
6999229        43202
6999230         1146
6999231         1230
6999232         1242
6999233         1220
6999234        37403
6999235        35651
6999236         2233
6999237        43215
6999238        37361
6999239        43307
6999240         1230
6999241         1212
6999242         1146
6999243        43285
6999244        43206
6999245        35305
6999246         1232
6999247        43069
6999248        30532
6999249        35107
6999250         1232

[6999251 rows x 7 columns]